name: Import the library

on:
  - push
  - pull_request

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Flit
        run: pip install flit

      - name: Install the package
        run: flit install

      - name: Import library
        run: python -c 'import discord_typings'
